/** Libellé affiché tant que l’utilisateur n’a pas choisi un pseudo personnalisé. */
export const PROFILE_USERNAME_DEFAULT_LABEL = 'username';

/**
 * Pseudo généré automatiquement (unicité en base). Affiché comme « username » dans l’UI.
 * - `username_` + hex (nouveau défaut)
 * - `u_` + 32 hex (ancien défaut)
 */
export function isAutoGeneratedProfileUsername(u: string | null | undefined): boolean {
  if (!u) return true;
  if (/^username_[0-9a-f]{8,32}$/i.test(u)) return true;
  if (/^u_[0-9a-f]{32}$/i.test(u)) return true;
  return false;
}

/** Texte à montrer après @ (Mon compte, profil public, etc.). */
export function profileUsernameDisplayLabel(stored: string | null | undefined): string {
  if (!stored || isAutoGeneratedProfileUsername(stored)) return PROFILE_USERNAME_DEFAULT_LABEL;
  return stored;
}

export const PROFILE_USERNAME_TAKEN_MESSAGE = 'Ce nom d’utilisateur est déjà pris. Choisis-en un autre.';

export function isUsernameUniqueViolation(err: unknown): boolean {
  if (!err || typeof err !== 'object') return false;
  const e = err as { code?: string; message?: string };
  if (e.code === '23505') return true;
  const m = e.message ?? '';
  return m.includes('profiles_username_key') || (m.includes('duplicate key') && m.includes('username'));
}

/** Message pour alert() / toast après échec UPDATE username. */
export function profileUsernameSaveErrorMessage(err: unknown): string {
  if (isUsernameUniqueViolation(err)) return PROFILE_USERNAME_TAKEN_MESSAGE;
  if (err && typeof err === 'object' && 'message' in err && typeof (err as { message: string }).message === 'string') {
    return (err as { message: string }).message;
  }
  return 'Impossible d’enregistrer le nom d’utilisateur.';
}
